name: Node CI

on: 
  pull_request:
    branches: 
      - master
      - dev
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies
      working-directory: '/src/personal-site'
      run: |
        npm install
      env:
        CI: true       
        
    - name: Build Project
      working-directory: '/src/personal-site'
      run: |
        npm run build
      env:
        CI: true
